import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'vi' | 'en';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Navigation
    'nav.dashboard': 'Trang chủ',
    'nav.exams': 'Đề thi',
    'nav.assignments': 'Bài tập',
    'nav.grades': 'Điểm số',
    'nav.gradebook': 'Sổ điểm',
    'nav.classes': 'Lớp học',
    'nav.profile': 'Hồ sơ',

    // Common
    'common.save': 'Lưu thay đổi',
    'common.saving': 'Đang lưu...',
    'common.loading': 'Đang tải...',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.delete': 'Xóa',
    'common.edit': 'Chỉnh sửa',
    'common.back': 'Quay lại',
    'common.search': 'Tìm kiếm',
    'common.verified': '✓',
    'common.view': 'Xem',
    'common.viewAll': 'Xem tất cả',
    'common.viewDetails': 'Xem chi tiết',
    'common.points': 'điểm',
    'common.questions': 'câu hỏi',
    'common.active': 'Đang mở',
    'common.draft': 'Bản nháp',
    'common.completed': 'Hoàn thành',
    'common.pending': 'Chờ xử lý',
    'common.total': 'Tổng',
    'common.processing': 'Đang xử lý...',
    'common.upload': 'Tải lên',
    'common.processingFile': 'Đang xử lý file...',
    'common.addQuestion': 'Thêm câu hỏi',
    'common.createExam': 'Tạo đề thi',
    'common.creating': 'Đang tạo...',
    'common.classNotFound': 'Không tìm thấy lớp học',
    'common.backToClasses': 'Quay lại danh sách lớp',
    'common.yes': 'Có',
    'common.no': 'Không',
    'common.student': 'học sinh',
    'common.students': 'học sinh',
    'common.exam': 'đề thi',
    'common.noTimeSet': 'Chưa cài đặt thời gian',
    'common.selectClass': 'Chọn lớp học',
    'common.inviteStudent': 'Mời học sinh',
    'common.remove': 'Xóa',
    'common.viewProfile': 'Xem hồ sơ',
    'common.deleteClass': 'Xóa lớp',
    'common.deleting': 'Đang xóa...',
    'common.deleteClassConfirm': 'Bạn có chắc chắn muốn xóa lớp này? Hành động này không thể hoàn tác.',
    'common.classSettings': 'Cài đặt lớp',
    'common.areYouSure': 'Bạn có chắc chắn muốn xóa',
    'common.fromThisClass': 'khỏi lớp học này?',
    'common.noData': 'Chưa có dữ liệu',
    'common.comingSoon': 'Sắp có',
    'common.featureDeveloping': 'Tính năng đang được phát triển',
    'common.pleaseComeBack': 'Vui lòng quay lại sau',
    'common.studentManagement': 'Quản lý học sinh',
    'common.gradeAnalytics': 'Thống kê điểm',
    'common.exportReports': 'Xuất báo cáo',
    'common.studentCount': 'học sinh',
    'common.noStudentsFound': 'Không tìm thấy học sinh',
    'common.noStudentsYet': 'Chưa có học sinh nào',
    'common.tryAdjustingSearch': 'Thử điều chỉnh từ khóa tìm kiếm',
    'common.shareClassCode': 'Chia sẻ mã lớp để mời học sinh',
    'common.classMembers': 'Thành viên lớp học',
    'common.enrolledStudents': 'học sinh đã đăng ký',
    'common.searchStudents': 'Tìm kiếm học sinh...',
    'common.copyClassCode': 'Sao chép mã lớp',
    'common.codeCopied': 'Đã sao chép mã lớp!',
    'null': 'N/A',
    'validation.invalidEmail': 'Vui lòng nhập địa chỉ email hợp lệ',
    'validation.passwordMinLength': 'Mật khẩu phải có ít nhất 6 ký tự',
    'validation.nameRequired': 'Tên phải có ít nhất 2 ký tự',
    'classCode': 'Mã lớp',

    // Pending Student Approval
    'pendingStudent.title': 'Yêu cầu tham gia lớp',
    'pendingStudent.pendingCount': 'học sinh đang chờ duyệt',
    'pendingStudent.noPending': 'Không có yêu cầu tham gia nào',
    'pendingStudent.waitingApproval': 'Đang chờ được duyệt',
    'pendingStudent.requestedAt': 'Yêu cầu lúc',
    'pendingStudent.approve': 'Duyệt',
    'pendingStudent.approving': 'Đang duyệt...',
    'pendingStudent.approved': 'Đã duyệt',
    'pendingStudent.reject': 'Từ chối',
    'pendingStudent.rejecting': 'Đang từ chối...',
    'pendingStudent.rejected': 'Đã từ chối',
    'pendingStudent.approvedSuccess': 'Đã duyệt học sinh tham gia lớp!',
    'pendingStudent.rejectedSuccess': 'Đã từ chối yêu cầu',
    'pendingStudent.approvedToast': 'đã được duyệt vào lớp',
    'pendingStudent.rejectedToast': 'đã bị từ chối',
    'pendingStudent.confirmReject': 'Bạn có chắc chắn muốn từ chối yêu cầu của',
    'pendingStudent.joinRequest': 'Yêu cầu tham gia lớp học',
    'pendingStudent.joinRequestDesc': 'Giáo viên sẽ xem xét và duyệt yêu cầu của bạn',
    'pendingStudent.status': 'Trạng thái',
    'pendingStudent.statusPending': 'Đang chờ duyệt',
    'pendingStudent.statusApproved': 'Đã được duyệt',
    'pendingStudent.statusRejected': 'Đã bị từ chối',
    'pendingStudent.statusWaiting': 'Đang chờ duyệt...',
    'pendingStudent.approvedJoin': 'Bạn đã được duyệt vào lớp!',
    'pendingStudent.rejectedJoin': 'Yêu cầu tham gia của bạn đã bị từ chối',
    'pendingStudent.joinWaiting': 'Vui lòng chờ giáo viên duyệt yêu cầu của bạn',

    // Profile
    'profile.title': 'Hồ sơ cá nhân',
    'profile.personal': 'Thông tin cá nhân',
    'profile.security': 'Bảo mật',
    'profile.preferences': 'Tùy chọn',
    'profile.notifications': 'Thông báo',
    'profile.name': 'Họ và tên',
    'profile.email': 'Email',
    'profile.phone': 'Số điện thoại',
    'profile.address': 'Địa chỉ',
    'profile.password': 'Mật khẩu',
    'profile.currentPassword': 'Mật khẩu hiện tại',
    'profile.newPassword': 'Mật khẩu mới',
    'profile.confirmPassword': 'Xác nhận mật khẩu',
    'profile.joinedDate': 'Ngày tham gia',
    'profile.back': 'Quay lại',
    'profile.emailVerified': 'Đã xác thực',
    'profile.datePending': '—',
    'profile.updateInfo': 'Cập nhật thông tin của bạn',
    'profile.accountSecurity': 'Bảo mật tài khoản',
    'profile.managePassword': 'Quản lý mật khẩu và bảo mật',
    'profile.customize': 'Tùy chỉnh trải nghiệm của bạn',
    'profile.notificationsDesc': 'Quản lý thông báo bạn nhận được',
    'profile.languageTitle': 'Ngôn ngữ / Language',
    'profile.saveChanges': 'Lưu thay đổi',
    'profile.updatePassword': 'Cập nhật mật khẩu',
    'profile.passwordTip': 'Để trống các ô mật khẩu nếu bạn không muốn thay đổi mật khẩu',
    'profile.enterNewPassword': 'Vui lòng nhập mật khẩu mới',
    'profile.currentPasswordRequired': 'Vui lòng nhập mật khẩu hiện tại',
    'profile.noEmail': 'Chưa cập nhật',
    'profile.stats.classes': 'Lớp học',
    'profile.stats.students': 'Học sinh',
    'profile.stats.exams': 'Kỳ thi',
    'profile.stats.assignments': 'Bài tập',
    'profile.stats.completed': 'Đã hoàn thành',
    'profile.stats.average': 'Điểm TB',

    // Notifications Settings
    'profile.notifications.assignment': 'Bài tập mới',
    'profile.notifications.assignmentDesc': 'Nhận thông báo khi có bài tập mới được giao',
    'profile.notifications.grade': 'Kết quả chấm điểm',
    'profile.notifications.gradeDesc': 'Nhận thông báo khi có điểm mới được cập nhật',
    'profile.notifications.exam': 'Đề thi mới',
    'profile.notifications.examDesc': 'Nhận thông báo khi có đề thi mới được tạo',
    'profile.notifications.class': 'Thông báo lớp học',
    'profile.notifications.classDesc': 'Nhận thông báo về hoạt động trong lớp học',
    'profile.manageNotifications': 'Quản lý thông báo',
    'profile.notifications.assignmentUpdates': 'Cập nhật bài tập',

    // Preferences Settings
    'profile.preferences.emailNotify': 'Thông báo qua Email',
    'profile.preferences.emailNotifyDesc': 'Nhận thông báo quan trọng qua email',
    'profile.preferences.weeklyDigest': 'Bản tin hàng tuần',
    'profile.preferences.weeklyDigestDesc': 'Nhận tóm tắt hoạt động hàng tuần vào thứ Hai',

    // Toast messages
    'toast.imageType': 'Vui lòng chọn file hình ảnh',
    'toast.imageSize': 'Kích thước ảnh phải nhỏ hơn 5MB',
    'toast.avatarSuccess': 'Cập nhật ảnh đại diện thành công!',
    'toast.uploadFailed': 'Tải ảnh lên thất bại',
    'toast.removeAvatarSuccess': 'Xóa ảnh đại diện thành công!',
    'toast.removeAvatarFailed': 'Xóa ảnh thất bại',
    'toast.passwordMin': 'Mật khẩu mới phải có ít nhất 6 ký tự',
    'toast.passwordMismatch': 'Mật khẩu mới không khớp',
    'toast.updateSuccess': 'Cập nhật thông tin thành công!',
    'toast.updateFailed': 'Cập nhật thất bại',
    'toast.loadDataFailed': 'Tải dữ liệu thất bại',
    'toast.loadClassesFailed': 'Tải danh sách lớp thất bại',
    'toast.loadExamsFailed': 'Tải danh sách đề thi thất bại',
    'toast.loadAssignmentsFailed': 'Tải danh sách bài tập thất bại',
    'toast.classCreated': 'Tạo lớp thành công!',
    'toast.classCodeCopied': 'Đã sao chép mã lớp!',
    'toast.failedLoadClass': 'Tải thông tin lớp thất bại',
    'toast.failedRemoveStudent': 'Lỗi khi xóa học sinh',
    'toast.classSettingsUpdated': 'Cập nhật cài đặt lớp thành công!',
    'toast.failedDeleteClass': 'Xóa lớp thất bại',
    'toast.removedFromClass': 'đã được xóa khỏi lớp',
    'toast.questionAdded': 'Đã thêm câu hỏi',
    'toast.enterQuestion': 'Vui lòng nhập câu hỏi',
    'toast.selectCorrectAnswer': 'Vui lòng chọn đáp án đúng',
    'toast.onlyDocxTxt': 'Chỉ chấp nhận file .txt hoặc .docx',
    'toast.addedQuestions': 'đã được thêm từ file!',
    'toast.noQuestionsInFile': 'Không tìm thấy câu hỏi trong file',
    'toast.parseFileFailed': 'Lỗi khi phân tích file',
    'toast.addAtLeastOne': 'Vui lòng thêm ít nhất một câu hỏi',
    'toast.examCreated': 'Tạo đề thi thành công!',
    'toast.createExamFailed': 'Tạo đề thi thất bại',
    'toast.noDueDate': 'Chưa có hạn nộp',
    'toast.editComingSoon': 'Chức năng chỉnh sửa sắp ra mắt',
    'toast.deleteComingSoon': 'Chức năng xóa sắp ra mắt',

    // Notifications
    'notify.newStudent': 'Học sinh mới đã tham gia lớp',
    'notify.examSubmission': 'Đã nhận bài thi',

    // Login
    'login.slogan': 'Hệ thống học & thi tiếng Anh',
    'login.welcomeBack': 'Chào mừng trở lại',
    'login.signInToContinue': 'Đăng nhập để tiếp tục',
    'login.createAccount': 'Tạo tài khoản',
    'login.joinToday': 'Tham gia ngay hôm nay',
    'login.email': 'Email',
    'login.password': 'Mật khẩu',
    'login.fullName': 'Họ và tên',
    'login.rememberMe': 'Ghi nhớ đăng nhập',
    'login.forgotPassword': 'Quên mật khẩu?',
    'login.signIn': 'Đăng nhập',
    'login.signingIn': 'Đang đăng nhập...',
    'login.orContinueWith': 'hoặc tiếp tục với',
    'login.continueWithGoogle': 'Đăng nhập bằng Google',
    'login.dontHaveAccount': 'Chưa có tài khoản?',
    'login.alreadyHaveAccount': 'Đã có tài khoản?',
    'login.signUp': 'Đăng ký',
    'login.signInLink': 'Đăng nhập',
    'login.demoAccount': 'Tài khoản demo',
    'login.resetPasswordDesc': 'Nhập email để nhận liên kết đặt lại mật khẩu',
    'login.enterEmail': 'Nhập email của bạn',
    'login.sendResetLink': 'Gửi liên kết đặt lại',
    'login.resetEmailSent': 'Đã gửi liên kết đặt lại mật khẩu!',
    'login.resetEmailNote': 'Vui lòng kiểm tra hộp thư email của bạn',
    'login.googleNotConfigured': 'Đăng nhập Google cần cấu hình Supabase',
    'toast.welcomeBack': 'Chào mừng bạn quay lại!',
    'toast.accountCreated': 'Tạo tài khoản thành công!',
    'toast.loginFailed': 'Đăng nhập thất bại',
    'toast.registrationFailed': 'Đăng ký thất bại',
    'auth.sessionExpired': 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',

    // Reset Password
    'auth.resetPassword': 'Quên mật khẩu',
    'auth.resetPasswordDesc': 'Nhập email của bạn để nhận liên kết đặt lại mật khẩu',
    'auth.setNewPassword': 'Đặt mật khẩu mới',
    'auth.setNewPasswordDesc': 'Nhập mật khẩu mới của bạn bên dưới',
    'auth.email': 'Email',
    'auth.newPassword': 'Mật khẩu mới',
    'auth.confirmPassword': 'Xác nhận mật khẩu',
    'auth.sendResetLink': 'Gửi liên kết đặt lại',
    'auth.resetEmailSent': 'Email đặt lại mật khẩu đã được gửi! Kiểm tra hộp thư của bạn.',
    'auth.updatePassword': 'Cập nhật mật khẩu',
    'auth.passwordUpdated': 'Mật khẩu đã được cập nhật thành công!',
    'auth.sending': 'Đang gửi...',
    'auth.updating': 'Đang cập nhật...',
    'auth.passwordMismatch': 'Mật khẩu không khớp',
    'auth.passwordTooShort': 'Mật khẩu phải có ít nhất 6 ký tự',
    'auth.backToLogin': 'Quay lại đăng nhập',
    'auth.securityNotice': 'Liên kết sẽ hết hạn sau 1 giờ. Vui lòng kiểm tra thư mục spam nếu không nhận được email.',
    'auth.noReceiveEmail': 'Không nhận được email?',
    'auth.resend': 'Gửi lại',
    'auth.waitBeforeResend': 'Vui lòng đợi trước khi gửi lại',
    'auth.seconds': 'giây',
    'auth.goToLogin': 'Đến trang đăng nhập',
    'auth.redirectToLogin': 'Đang chuyển hướng đến trang đăng nhập...',
    'auth.rateLimitExceeded': 'Quá nhiều yêu cầu. Vui lòng thử lại sau.',
    'auth.sendFailed': 'Gửi email thất bại',
    'auth.resetEmailResent': 'Email reset đã được gửi lại!',

    // Features
    'features.secure': 'Bảo mật',
    'features.easyToUse': 'Dễ sử dụng',
    'features.englishLearning': 'Học Tiếng Anh',

    // Dashboard
    'dashboard.welcome': 'Xin chào',
    'dashboard.teacher': 'Giáo viên',
    'dashboard.totalStudents': 'Tổng học sinh',
    'dashboard.activeExams': 'Đề thi đang mở',
    'dashboard.pendingAssignments': 'Bài tập chờ chấm',
    'dashboard.quickActions': 'Hành động nhanh',
    'dashboard.createClass': 'Tạo lớp mới',
    'dashboard.createExam': 'Tạo đề thi',
    'dashboard.createAssignment': 'Tạo bài tập',
    'dashboard.goodMorning': 'Chào buổi sáng',
    'dashboard.goodAfternoon': 'Chào buổi chiều',
    'dashboard.goodEvening': 'Chào buổi tối',
    'dashboard.totalClasses': 'Tổng số lớp',
    'dashboard.yourClasses': 'Lớp học của bạn',
    'dashboard.recentExams': 'Đề thi gần đây',
    'dashboard.overview': 'Tổng quan',
    'dashboard.completion': 'Hoàn thành',
    'dashboard.createClassStart': 'Tạo lớp học để bắt đầu',
    'dashboard.addExamsMetrics': 'Thêm đề thi để xem thống kê',
    'dashboard.noData': 'Chưa có dữ liệu',
    'dashboard.newExam': 'Đề thi mới',
    'dashboard.gradebook': 'Sổ điểm',
    'dashboard.results': 'Kết quả',
    'dashboard.classes': 'Lớp học',

    // Classes
    'classes.title': 'Danh sách lớp học',
    'classes.create': 'Tạo lớp mới',
    'classes.className': 'Tên lớp',
    'classes.classCode': 'Mã lớp',
    'classes.students': 'Học sinh',
    'classes.exams': 'Đề thi',
    'classes.assignments': 'Bài tập',
    'classes.delete': 'Xóa lớp',
    'classes.deleteConfirm': 'Bạn có chắc chắn muốn xóa lớp này?',
    'classes.deleteSuccess': 'Xóa lớp thành công!',
    'classes.empty': 'Chưa có lớp học nào',
    'classes.searchPlaceholder': 'Tìm kiếm lớp học...',
    'classes.createFirstClass': 'Tạo lớp học đầu tiên để bắt đầu',
    'classes.createNewClass': 'Tạo lớp học mới',
    'classes.enterClassName': 'Nhập tên lớp học',

    // Exams
    'exams.title': 'Đề thi',
    'exams.create': 'Tạo đề thi',
    'exams.duration': 'Thời gian',
    'exams.questions': 'Số câu hỏi',
    'exams.startTime': 'Thời gian bắt đầu',
    'exams.endTime': 'Thời gian kết thúc',
    'exams.totalPoints': 'Tổng điểm',
    'exams.status': 'Trạng thái',
    'exams.all': 'Tất cả',
    'exams.active': 'Đang mở',
    'exams.closed': 'Đã đóng',
    'exams.draft': 'Bản nháp',
    'exams.submissions': 'Bài nộp',
    'exams.viewSubmissions': 'Xem bài nộp',
    'exams.delete': 'Xóa đề thi',
    'exams.deleteConfirm': 'Bạn có chắc chắn muốn xóa đề thi này?',
    'exams.empty': 'Chưa có đề thi nào',
    'exams.createExamGetStarted': 'Tạo đề thi đầu tiên để bắt đầu',
    'exams.manageExams': 'Quản lý đề thi',
    'exams.createManageExams': 'Tạo và quản lý đề thi cho học sinh',
    'exams.allExams': 'Tất cả đề thi',
    'exams.examCount': 'đề thi',
    'exams.code': 'Mã đề thi',
    'exams.schedule': 'Lịch thi',
    'exams.details': 'Chi tiết',
    'exams.actions': 'Hành động',
    'exams.viewDetails': 'Xem chi tiết',

    // Assignments
    'assignments.title': 'Bài tập',
    'assignments.create': 'Tạo bài tập',
    'assignments.dueDate': 'Hạn nộp',
    'assignments.totalPoints': 'Tổng điểm',
    'assignments.submissions': 'Bài nộp',
    'assignments.viewSubmissions': 'Xem bài nộp',
    'assignments.delete': 'Xóa bài tập',
    'assignments.deleteConfirm': 'Bạn có chắc chắn muốn xóa bài tập này?',
    'assignments.empty': 'Chưa có bài tập nào',
    'assignments.manageAssignments': 'Quản lý bài tập',
    'assignments.createGradeAssignments': 'Tạo và chấm bài tập cho học sinh',
    'assignments.allAssignments': 'Tất cả bài tập',
    'assignments.assignmentCount': 'bài tập',
    'assignments.class': 'Lớp học',
    'assignments.details': 'Chi tiết',
    'assignments.noDueDate': 'Không có hạn nộp',
    'assignments.createAssignmentGetStarted': 'Tạo bài tập đầu tiên để bắt đầu',

    // Gradebook
    'gradebook.title': 'Sổ điểm',
    'gradebook.student': 'Học sinh',
    'gradebook.exam': 'Đề thi',
    'gradebook.assignment': 'Bài tập',
    'gradebook.score': 'Điểm',
    'gradebook.empty': 'Chưa có dữ liệu',

    // Notifications
    'notifications.title': 'Thông báo',
    'notifications.empty': 'Không có thông báo',

    // Language
    'settings.language': 'Ngôn ngữ',
    'settings.vietnamese': 'Tiếng Việt',
    'settings.english': 'English',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.exams': 'Exams',
    'nav.assignments': 'Assignments',
    'nav.grades': 'Grades',
    'nav.gradebook': 'Gradebook',
    'nav.classes': 'My Classes',
    'nav.profile': 'Profile',

    // Common
    'common.save': 'Save Changes',
    'common.saving': 'Saving...',
    'common.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.search': 'Search',
    'common.verified': '✓',
    'common.view': 'View',
    'common.viewAll': 'View All',
    'common.viewDetails': 'View Details',
    'common.points': 'points',
    'common.questions': 'questions',
    'common.active': 'Active',
    'common.draft': 'Draft',
    'common.completed': 'Completed',
    'common.pending': 'Pending',
    'common.total': 'Total',
    'common.processing': 'Processing...',
    'common.upload': 'Upload',
    'common.processingFile': 'Processing file...',
    'common.addQuestion': 'Add Question',
    'common.createExam': 'Create Exam',
    'common.creating': 'Creating...',
    'common.classNotFound': 'Class not found',
    'common.backToClasses': 'Back to Classes',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.student': 'student',
    'common.students': 'students',
    'common.exam': 'exam',
    'common.noTimeSet': 'No time set',
    'common.selectClass': 'Select a class',
    'common.inviteStudent': 'Invite Student',
    'common.remove': 'Remove',
    'common.viewProfile': 'View Profile',
    'common.deleteClass': 'Delete Class',
    'common.deleting': 'Deleting...',
    'common.deleteClassConfirm': 'Are you sure you want to delete this class? This action cannot be undone.',
    'common.classSettings': 'Class Settings',
    'common.areYouSure': 'Are you sure you want to remove',
    'common.fromThisClass': 'from this class?',
    'common.noData': 'No data yet',
    'common.comingSoon': 'Coming Soon',
    'common.featureDeveloping': 'Feature is under development',
    'common.pleaseComeBack': 'Please come back later',
    'common.studentManagement': 'Student Management',
    'common.gradeAnalytics': 'Grade Analytics',
    'common.exportReports': 'Export Reports',
    'common.studentCount': 'students',
    'common.noStudentsFound': 'No students found',
    'common.noStudentsYet': 'No students yet',
    'common.tryAdjustingSearch': 'Try adjusting your search terms',
    'common.shareClassCode': 'Share the class code to invite students',
    'common.classMembers': 'Class Members',
    'common.enrolledStudents': 'students enrolled',
    'common.searchStudents': 'Search students...',
    'common.copyClassCode': 'Copy class code',
    'common.codeCopied': 'Class code copied!',
    'null': 'N/A',
    'validation.invalidEmail': 'Please enter a valid email address',
    'validation.passwordMinLength': 'Password must be at least 6 characters',
    'validation.nameRequired': 'Name must be at least 2 characters',
    'classCode': 'Class Code',

    // Pending Student Approval
    'pendingStudent.title': 'Join Requests',
    'pendingStudent.pendingCount': 'students waiting for approval',
    'pendingStudent.noPending': 'No pending join requests',
    'pendingStudent.waitingApproval': 'Waiting for approval',
    'pendingStudent.requestedAt': 'Requested at',
    'pendingStudent.approve': 'Approve',
    'pendingStudent.approving': 'Approving...',
    'pendingStudent.approved': 'Approved',
    'pendingStudent.reject': 'Reject',
    'pendingStudent.rejecting': 'Rejecting...',
    'pendingStudent.rejected': 'Rejected',
    'pendingStudent.approvedSuccess': 'Student approved to join the class!',
    'pendingStudent.rejectedSuccess': 'Request rejected',
    'pendingStudent.approvedToast': 'has been approved to join the class',
    'pendingStudent.rejectedToast': 'has been rejected',
    'pendingStudent.confirmReject': 'Are you sure you want to reject the request from',
    'pendingStudent.joinRequest': 'Class Join Request',
    'pendingStudent.joinRequestDesc': 'Your teacher will review and approve your request',
    'pendingStudent.status': 'Status',
    'pendingStudent.statusPending': 'Pending approval',
    'pendingStudent.statusApproved': 'Approved',
    'pendingStudent.statusRejected': 'Rejected',
    'pendingStudent.statusWaiting': 'Waiting for approval...',
    'pendingStudent.approvedJoin': 'You have been approved to join the class!',
    'pendingStudent.rejectedJoin': 'Your join request has been rejected',
    'pendingStudent.joinWaiting': 'Please wait for your teacher to approve your request',

    // Profile
    'profile.title': 'Personal Profile',
    'profile.personal': 'Personal Information',
    'profile.security': 'Security',
    'profile.preferences': 'Preferences',
    'profile.notifications': 'Notifications',
    'profile.name': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.address': 'Address',
    'profile.password': 'Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm Password',
    'profile.joinedDate': 'Joined Date',
    'profile.back': 'Back',
    'profile.emailVerified': 'Verified',
    'profile.datePending': '—',
    'profile.updateInfo': 'Update your information',
    'profile.accountSecurity': 'Account Security',
    'profile.managePassword': 'Manage password and security',
    'profile.customize': 'Customize your experience',
    'profile.notificationsDesc': 'Manage notifications you receive',
    'profile.languageTitle': 'Language / Ngôn ngữ',
    'profile.saveChanges': 'Save Changes',
    'profile.updatePassword': 'Update Password',
    'profile.passwordTip': 'Leave password fields empty if you do not want to change password',
    'profile.enterNewPassword': 'Please enter a new password',
    'profile.currentPasswordRequired': 'Please enter your current password',
    'profile.noEmail': 'Not provided',
    'profile.stats.classes': 'Classes',
    'profile.stats.students': 'Students',
    'profile.stats.exams': 'Exams',
    'profile.stats.assignments': 'Assignments',
    'profile.stats.completed': 'Completed',
    'profile.stats.average': 'Average',

    // Notifications Settings
    'profile.notifications.assignment': 'New Assignments',
    'profile.notifications.assignmentDesc': 'Get notified when new assignments are given',
    'profile.notifications.grade': 'Graded Results',
    'profile.notifications.gradeDesc': 'Get notified when new scores are available',
    'profile.notifications.exam': 'New Exams',
    'profile.notifications.examDesc': 'Get notified when new exams are created',
    'profile.notifications.class': 'Class Updates',
    'profile.notifications.classDesc': 'Get notified about activity in your classes',
    'profile.manageNotifications': 'Manage Notifications',
    'profile.notifications.assignmentUpdates': 'Assignment Updates',

    // Preferences Settings
    'profile.preferences.emailNotify': 'Email Notifications',
    'profile.preferences.emailNotifyDesc': 'Receive important notifications via email',
    'profile.preferences.weeklyDigest': 'Weekly Digest',
    'profile.preferences.weeklyDigestDesc': 'Receive weekly activity summary every Monday',

    // Toast messages
    'toast.imageType': 'Please select an image file',
    'toast.imageSize': 'Image size must be less than 5MB',
    'toast.avatarSuccess': 'Avatar updated successfully!',
    'toast.uploadFailed': 'Failed to upload image',
    'toast.removeAvatarSuccess': 'Avatar removed successfully!',
    'toast.removeAvatarFailed': 'Failed to remove avatar',
    'toast.passwordMin': 'New password must be at least 6 characters',
    'toast.passwordMismatch': 'New passwords do not match',
    'toast.updateSuccess': 'Profile updated successfully!',
    'toast.updateFailed': 'Update failed',
    'toast.loadDataFailed': 'Failed to load data',
    'toast.loadClassesFailed': 'Failed to load classes',
    'toast.loadExamsFailed': 'Failed to load exams',
    'toast.loadAssignmentsFailed': 'Failed to load assignments',
    'toast.classCreated': 'Class created successfully!',
    'toast.classCodeCopied': 'Class code copied!',
    'toast.failedLoadClass': 'Failed to load class information',
    'toast.failedRemoveStudent': 'Error removing student',
    'toast.classSettingsUpdated': 'Class settings updated!',
    'toast.failedDeleteClass': 'Failed to delete class',
    'toast.removedFromClass': 'has been removed from the class',
    'toast.questionAdded': 'Question added',
    'toast.enterQuestion': 'Please enter a question',
    'toast.selectCorrectAnswer': 'Please select the correct answer',
    'toast.onlyDocxTxt': 'Only .txt or .docx files are accepted',
    'toast.addedQuestions': 'questions added from file!',
    'toast.noQuestionsInFile': 'No questions found in file',
    'toast.parseFileFailed': 'Failed to parse file',
    'toast.addAtLeastOne': 'Please add at least one question',
    'toast.examCreated': 'Exam created successfully!',
    'toast.createExamFailed': 'Failed to create exam',
    'toast.noDueDate': 'No due date',
    'toast.editComingSoon': 'Edit functionality coming soon',
    'toast.deleteComingSoon': 'Delete functionality coming soon',

    // Notifications
    'notify.newStudent': 'New student joined class',
    'notify.examSubmission': 'Exam submission received',

    // Login
    'login.slogan': 'English Learning & Exam System',
    'login.welcomeBack': 'Welcome Back',
    'login.signInToContinue': 'Sign in to continue',
    'login.createAccount': 'Create Account',
    'login.joinToday': 'Join us today',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.fullName': 'Full Name',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.orContinueWith': 'or continue with',
    'login.continueWithGoogle': 'Continue with Google',
    'login.dontHaveAccount': "Don't have an account?",
    'login.alreadyHaveAccount': 'Already have an account?',
    'login.signUp': 'Sign Up',
    'login.signInLink': 'Sign In',
    'login.demoAccount': 'Demo Account',
    'login.resetPasswordDesc': 'Enter your email to receive a password reset link',
    'login.enterEmail': 'Enter your email',
    'login.sendResetLink': 'Send Reset Link',
    'login.resetEmailSent': 'Password reset link sent!',
    'login.resetEmailNote': 'Please check your email inbox',
    'login.googleNotConfigured': 'Google login requires Supabase configuration',
    'toast.welcomeBack': 'Welcome back!',
    'toast.accountCreated': 'Account created successfully!',
    'toast.loginFailed': 'Login failed',
    'toast.registrationFailed': 'Registration failed',
    'auth.sessionExpired': 'Your session has expired. Please login again.',

    // Reset Password
    'auth.resetPassword': 'Forgot Password',
    'auth.resetPasswordDesc': 'Enter your email to receive a password reset link',
    'auth.setNewPassword': 'Set New Password',
    'auth.setNewPasswordDesc': 'Enter your new password below',
    'auth.email': 'Email',
    'auth.newPassword': 'New Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.resetEmailSent': 'Password reset email sent! Check your inbox.',
    'auth.updatePassword': 'Update Password',
    'auth.passwordUpdated': 'Password updated successfully!',
    'auth.sending': 'Sending...',
    'auth.updating': 'Updating...',
    'auth.passwordMismatch': 'Passwords do not match',
    'auth.passwordTooShort': 'Password must be at least 6 characters',
    'auth.backToLogin': 'Back to Login',
    'auth.securityNotice': 'The link will expire in 1 hour. Please check your spam folder if you do not receive the email.',
    'auth.noReceiveEmail': "Didn't receive the email?",
    'auth.resend': 'Resend',
    'auth.waitBeforeResend': 'Please wait before resending',
    'auth.seconds': 'seconds',
    'auth.goToLogin': 'Go to Login',
    'auth.redirectToLogin': 'Redirecting to login page...',
    'auth.rateLimitExceeded': 'Too many requests. Please try again later.',
    'auth.sendFailed': 'Failed to send email',
    'auth.resetEmailResent': 'Reset email has been resent!',

    // Features
    'features.secure': 'Secure',
    'features.easyToUse': 'Easy to Use',
    'features.englishLearning': 'English Learning',

    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.teacher': 'Teacher',
    'dashboard.totalStudents': 'Total Students',
    'dashboard.activeExams': 'Active Exams',
    'dashboard.pendingAssignments': 'Pending Assignments',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.createClass': 'Create New Class',
    'dashboard.createExam': 'Create Exam',
    'dashboard.createAssignment': 'Create Assignment',
    'dashboard.goodMorning': 'Good Morning',
    'dashboard.goodAfternoon': 'Good Afternoon',
    'dashboard.goodEvening': 'Good Evening',
    'dashboard.totalClasses': 'Total Classes',
    'dashboard.yourClasses': 'Your Classes',
    'dashboard.recentExams': 'Recent Exams',
    'dashboard.overview': 'Overview',
    'dashboard.completion': 'Completion',
    'dashboard.createClassStart': 'Create a class to start tracking',
    'dashboard.addExamsMetrics': 'Add exams to see more metrics',
    'dashboard.noData': 'No data yet',
    'dashboard.newExam': 'New Exam',
    'dashboard.gradebook': 'Gradebook',
    'dashboard.results': 'Results',
    'dashboard.classes': 'Classes',

    // Classes
    'classes.title': 'My Classes',
    'classes.create': 'Create Class',
    'classes.className': 'Class Name',
    'classes.classCode': 'Class Code',
    'classes.students': 'Students',
    'classes.exams': 'Exams',
    'classes.assignments': 'Assignments',
    'classes.delete': 'Delete Class',
    'classes.deleteConfirm': 'Are you sure you want to delete this class?',
    'classes.deleteSuccess': 'Class deleted successfully!',
    'classes.empty': 'No classes yet',
    'classes.searchPlaceholder': 'Search classes...',
    'classes.createFirstClass': 'Create your first class to get started',
    'classes.createNewClass': 'Create New Class',
    'classes.enterClassName': 'Enter class name',

    // Exams
    'exams.title': 'Exams',
    'exams.create': 'Create Exam',
    'exams.duration': 'Duration',
    'exams.questions': 'Questions',
    'exams.startTime': 'Start Time',
    'exams.endTime': 'End Time',
    'exams.totalPoints': 'Total Points',
    'exams.status': 'Status',
    'exams.all': 'All',
    'exams.active': 'Active',
    'exams.closed': 'Closed',
    'exams.draft': 'Draft',
    'exams.submissions': 'Submissions',
    'exams.viewSubmissions': 'View Submissions',
    'exams.delete': 'Delete Exam',
    'exams.deleteConfirm': 'Are you sure you want to delete this exam?',
    'exams.empty': 'No exams yet',
    'exams.createExamGetStarted': 'Create your first exam to get started',
    'exams.manageExams': 'Manage Exams',
    'exams.createManageExams': 'Create and manage exams for students',
    'exams.allExams': 'All Exams',
    'exams.examCount': 'exams',
    'exams.code': 'Exam Code',
    'exams.schedule': 'Schedule',
    'exams.details': 'Details',
    'exams.actions': 'Actions',
    'exams.viewDetails': 'View Details',
    'exams.questionsCount': 'questions',

    // Assignments
    'assignments.title': 'Assignments',
    'assignments.create': 'Create Assignment',
    'assignments.dueDate': 'Due Date',
    'assignments.totalPoints': 'Total Points',
    'assignments.submissions': 'Submissions',
    'assignments.viewSubmissions': 'View Submissions',
    'assignments.delete': 'Delete Assignment',
    'assignments.deleteConfirm': 'Are you sure you want to delete this assignment?',
    'assignments.empty': 'No assignments yet',
    'assignments.manageAssignments': 'Manage Assignments',
    'assignments.createGradeAssignments': 'Create and grade assignments for students',
    'assignments.allAssignments': 'All Assignments',
    'assignments.assignmentCount': 'assignments',
    'assignments.class': 'Class',
    'assignments.details': 'Details',
    'assignments.noDueDate': 'No due date',
    'assignments.createAssignmentGetStarted': 'Create your first assignment to get started',

    // Gradebook
    'gradebook.title': 'Gradebook',
    'gradebook.student': 'Student',
    'gradebook.exam': 'Exam',
    'gradebook.assignment': 'Assignment',
    'gradebook.score': 'Score',
    'gradebook.empty': 'No data yet',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.empty': 'No notifications',

    // Language
    'settings.language': 'Language',
    'settings.vietnamese': 'Tiếng Việt',
    'settings.english': 'English',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    if (saved && (saved === 'vi' || saved === 'en')) {
      return saved as Language;
    }
    return 'vi';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
    window.dispatchEvent(new CustomEvent('languageChange', { detail: lang }));
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

