import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'vi' | 'en';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Navigation
    'nav.dashboard': 'Trang chủ',
    'nav.courses': 'Khóa học',
    'nav.assignments': 'Bài tập',
    'nav.exams': 'Đề thi',
    'nav.grades': 'Điểm số',
    'nav.notifications': 'Thông báo',
    'nav.profile': 'Hồ sơ',
    'nav.joinClass': 'Tham gia lớp',

    // Common
    'common.save': 'Lưu thay đổi',
    'common.saving': 'Đang lưu...',
    'common.loading': 'Đang tải...',
    'common.cancel': 'Hủy',
    'common.confirm': 'Xác nhận',
    'common.delete': 'Xóa',
    'common.edit': 'Chỉnh sửa',
    'common.back': 'Quay lại',
    'common.search': 'Tìm kiếm',
    'common.verified': 'Đã xác thực',
    'common.view': 'Xem',
    'common.viewAll': 'Xem tất cả',
    'common.viewDetails': 'Xem chi tiết',
    'common.points': 'điểm',
    'common.questions': 'câu hỏi',
    'common.active': 'Đang mở',
    'common.draft': 'Bản nháp',
    'common.completed': 'Hoàn thành',
    'common.pending': 'Chờ xử lý',
    'common.total': 'Tổng',
    'common.processing': 'Đang xử lý...',
    'common.noData': 'Chưa có dữ liệu',
    'common.comingSoon': 'Sắp có',
    'common.featureDeveloping': 'Tính năng đang được phát triển',
    'common.pleaseComeBack': 'Vui lòng quay lại sau',
    'common.student': 'học sinh',
    'common.students': 'học sinh',
    'common.class': 'lớp học',
    'common.classes': 'lớp học',
    'common.noClasses': 'Chưa có lớp học nào',
    'common.noClassesYet': 'Chưa có lớp học nào',
    'common.joinClass': 'Tham gia lớp học',
    'common.enterClassCode': 'Nhập mã lớp',
    'common.classCode': 'Mã lớp',
    'common.classCodePlaceholder': 'Nhập mã lớp học',
    'common.join': 'Tham gia',
    'common.joining': 'Đang tham gia...',
    'common.joinSuccess': 'Tham gia lớp thành công!',
    'common.joinFailed': 'Tham gia lớp thất bại',
    'common.invalidCode': 'Mã lớp không hợp lệ',
    'common.classNotFound': 'Không tìm thấy lớp học',
    'common.youJoinedClass': 'Bạn đã tham gia lớp này rồi',
    'common.pendingApproval': 'Đang chờ duyệt',
    'common.approved': 'Đã duyệt',
    'common.rejected': 'Đã từ chối',
    'common.teacher': 'Giáo viên',
    'common.teacherRole': 'Giáo viên',
    'common.logout': 'Đăng xuất',
    'common.settings': 'Cài đặt',

    // Profile
    'profile.title': 'Hồ sơ cá nhân',
    'profile.personal': 'Thông tin cá nhân',
    'profile.security': 'Bảo mật',
    'profile.preferences': 'Tùy chọn',
    'profile.notifications': 'Thông báo',
    'profile.name': 'Họ và tên',
    'profile.email': 'Email',
    'profile.phone': 'Số điện thoại',
    'profile.address': 'Địa chỉ',
    'profile.password': 'Mật khẩu',
    'profile.currentPassword': 'Mật khẩu hiện tại',
    'profile.newPassword': 'Mật khẩu mới',
    'profile.confirmPassword': 'Xác nhận mật khẩu',
    'profile.joinedDate': 'Ngày tham gia',
    'profile.back': 'Quay lại',
    'profile.emailVerified': 'Đã xác thực',
    'profile.datePending': '—',
    'profile.updateInfo': 'Cập nhật thông tin của bạn',
    'profile.accountSecurity': 'Bảo mật tài khoản',
    'profile.managePassword': 'Quản lý mật khẩu và bảo mật',
    'profile.customize': 'Tùy chỉnh trải nghiệm của bạn',
    'profile.notificationsDesc': 'Quản lý thông báo bạn nhận được',
    'profile.languageTitle': 'Ngôn ngữ / Language',
    'profile.saveChanges': 'Lưu thay đổi',
    'profile.updatePassword': 'Cập nhật mật khẩu',
    'profile.passwordTip': 'Để trống các ô mật khẩu nếu bạn không muốn thay đổi mật khẩu',
    'profile.enterNewPassword': 'Vui lòng nhập mật khẩu mới',
    'profile.currentPasswordRequired': 'Vui lòng nhập mật khẩu hiện tại',
    'profile.noEmail': 'Chưa cập nhật',
    'profile.stats.courses': 'Khóa học',
    'profile.stats.assignments': 'Bài tập',
    'profile.stats.exams': 'Kỳ thi',
    'profile.stats.completed': 'Đã hoàn thành',
    'profile.stats.average': 'Điểm TB',

    // Toast messages
    'toast.imageType': 'Vui lòng chọn file hình ảnh',
    'toast.imageSize': 'Kích thước ảnh phải nhỏ hơn 5MB',
    'toast.avatarSuccess': 'Cập nhật ảnh đại diện thành công!',
    'toast.uploadFailed': 'Tải ảnh lên thất bại',
    'toast.removeAvatarSuccess': 'Xóa ảnh đại diện thành công!',
    'toast.removeAvatarFailed': 'Xóa ảnh thất bại',
    'toast.passwordMin': 'Mật khẩu mới phải có ít nhất 6 ký tự',
    'toast.passwordMismatch': 'Mật khẩu mới không khớp',
    'toast.updateSuccess': 'Cập nhật thông tin thành công!',
    'toast.updateFailed': 'Cập nhật thất bại',
    'toast.loadDataFailed': 'Tải dữ liệu thất bại',
    'toast.loadCoursesFailed': 'Tải danh sách khóa học thất bại',
    'toast.loadAssignmentsFailed': 'Tải danh sách bài tập thất bại',
    'toast.loadExamsFailed': 'Tải danh sách đề thi thất bại',
    'toast.loadGradesFailed': 'Tải điểm số thất bại',
    'toast.logoutSuccess': 'Đăng xuất thành công!',

    // Login
    'login.slogan': 'Hệ thống học & thi tiếng Anh',
    'login.welcomeBack': 'Chào mừng trở lại',
    'login.signInToContinue': 'Đăng nhập để tiếp tục',
    'login.createAccount': 'Tạo tài khoản',
    'login.joinToday': 'Tham gia ngay hôm nay',
    'login.email': 'Email',
    'login.password': 'Mật khẩu',
    'login.fullName': 'Họ và tên',
    'login.rememberMe': 'Ghi nhớ đăng nhập',
    'login.forgotPassword': 'Quên mật khẩu?',
    'login.signIn': 'Đăng nhập',
    'login.signingIn': 'Đang đăng nhập...',
    'login.orContinueWith': 'hoặc tiếp tục với',
    'login.continueWithGoogle': 'Đăng nhập bằng Google',
    'login.dontHaveAccount': 'Chưa có tài khoản?',
    'login.alreadyHaveAccount': 'Đã có tài khoản?',
    'login.signUp': 'Đăng ký',
    'login.signInLink': 'Đăng nhập',
    'login.demoAccount': 'Tài khoản demo',
    'login.resetPasswordDesc': 'Nhập email để nhận liên kết đặt lại mật khẩu',
    'login.enterEmail': 'Nhập email của bạn',
    'login.sendResetLink': 'Gửi liên kết đặt lại',
    'login.resetEmailSent': 'Đã gửi liên kết đặt lại mật khẩu!',
    'login.resetEmailNote': 'Vui lòng kiểm tra hộp thư email của bạn',
    'login.googleNotConfigured': 'Đăng nhập Google cần cấu hình Supabase',
    'toast.welcomeBack': 'Chào mừng bạn quay lại!',
    'toast.accountCreated': 'Tạo tài khoản thành công!',
    'toast.loginFailed': 'Đăng nhập thất bại',
    'toast.registrationFailed': 'Đăng ký thất bại',
    'auth.sessionExpired': 'Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',

    // Dashboard
    'dashboard.welcome': 'Xin chào',
    'dashboard.student': 'Học sinh',
    'dashboard.yourCourses': 'Khóa học của bạn',
    'dashboard.yourAssignments': 'Bài tập của bạn',
    'dashboard.upcomingExams': 'Đề thi sắp tới',
    'dashboard.recentGrades': 'Điểm số gần đây',
    'dashboard.goodMorning': 'Chào buổi sáng',
    'dashboard.goodAfternoon': 'Chào buổi chiều',
    'dashboard.goodEvening': 'Chào buổi tối',
    'dashboard.totalCourses': 'Tổng số khóa học',
    'dashboard.pendingAssignments': 'Bài tập chờ nộp',
    'dashboard.completedExams': 'Đề thi đã hoàn thành',
    'dashboard.quickActions': 'Hành động nhanh',
    'dashboard.joinNewClass': 'Tham gia lớp mới',
    'dashboard.viewGrades': 'Xem điểm số',
    'dashboard.viewAssignments': 'Xem bài tập',
    'dashboard.viewExams': 'Xem đề thi',
    'dashboard.noCourses': 'Chưa có khóa học nào',
    'dashboard.noCoursesDesc': 'Tham gia một lớp học để bắt đầu',
    'dashboard.noData': 'Chưa có dữ liệu',
    'dashboard.joinClassStart': 'Tham gia lớp học để bắt đầu',

    // Courses
    'courses.title': 'Khóa học',
    'courses.myCourses': 'Khóa học của tôi',
    'courses.className': 'Tên lớp',
    'courses.teacher': 'Giáo viên',
    'courses.students': 'Học sinh',
    'courses.assignments': 'Bài tập',
    'courses.exams': 'Đề thi',
    'courses.empty': 'Chưa có khóa học nào',
    'courses.emptyDesc': 'Tham gia một lớp học để bắt đầu',
    'courses.searchPlaceholder': 'Tìm kiếm khóa học...',
    'courses.joinClass': 'Tham gia lớp học',
    'courses.courseCount': 'khóa học',
    'courses.viewDetails': 'Xem chi tiết',

    // Assignments
    'assignments.title': 'Bài tập',
    'assignments.myAssignments': 'Bài tập của tôi',
    'assignments.dueDate': 'Hạn nộp',
    'assignments.totalPoints': 'Tổng điểm',
    'assignments.yourScore': 'Điểm của bạn',
    'assignments.submitted': 'Đã nộp',
    'assignments.notSubmitted': 'Chưa nộp',
    'assignments.graded': 'Đã chấm',
    'assignments.pending': 'Chưa chấm',
    'assignments.empty': 'Chưa có bài tập nào',
    'assignments.emptyDesc': 'Bạn chưa có bài tập nào trong các lớp đã tham gia',
    'assignments.searchPlaceholder': 'Tìm kiếm bài tập...',
    'assignments.allAssignments': 'Tất cả bài tập',
    'assignments.assignmentCount': 'bài tập',
    'assignments.class': 'Lớp học',
    'assignments.noDueDate': 'Không có hạn nộp',
    'assignments.overdue': 'Quá hạn',
    'assignments.turnIn': 'Nộp bài',
    'assignments.viewSubmission': 'Xem bài đã nộp',

    // Exams
    'exams.title': 'Đề thi',
    'exams.myExams': 'Đề thi của tôi',
    'exams.duration': 'Thời gian',
    'exams.questions': 'Số câu hỏi',
    'exams.startTime': 'Thời gian bắt đầu',
    'exams.endTime': 'Thời gian kết thúc',
    'exams.totalPoints': 'Tổng điểm',
    'exams.yourScore': 'Điểm của bạn',
    'exams.status': 'Trạng thái',
    'exams.all': 'Tất cả',
    'exams.active': 'Đang mở',
    'exams.closed': 'Đã đóng',
    'exams.draft': 'Bản nháp',
    'exams.submitted': 'Đã nộp',
    'exams.notSubmitted': 'Chưa nộp',
    'exams.viewResults': 'Xem kết quả',
    'exams.takeExam': 'Làm bài thi',
    'exams.empty': 'Chưa có đề thi nào',
    'exams.emptyDesc': 'Bạn chưa có đề thi nào trong các lớp đã tham gia',
    'exams.searchPlaceholder': 'Tìm kiếm đề thi...',
    'exams.allExams': 'Tất cả đề thi',
    'exams.examCount': 'đề thi',
    'exams.upcoming': 'Sắp diễn ra',
    'exams.inProgress': 'Đang diễn ra',
    'exams.completed': 'Đã hoàn thành',
    'exams.notStarted': 'Chưa bắt đầu',
    'exams.timeRemaining': 'Thời gian còn lại',
    'exams.startExam': 'Bắt đầu thi',
    'exams.submitExam': 'Nộp bài',
    'exams.confirmSubmit': 'Bạn có chắc chắn muốn nộp bài?',
    'exams.examCode': 'Mã đề thi',

    // Grades
    'grades.title': 'Bảng điểm',
    'grades.subtitle': 'Xem và theo dõi điểm số của bạn',
    'grades.selectCourse': 'Chọn khóa học',
    'grades.noGrades': 'Chưa có điểm số nào',
    'grades.noGradesDesc': 'Bạn chưa có điểm nào trong các lớp đã tham gia',
    'grades.searchPlaceholder': 'Tìm kiếm điểm số...',
    'grades.studentList': 'Bảng điểm',
    'grades.students': 'học sinh',
    'grades.exams': 'bài thi',
    'grades.assignments': 'bài tập',
    'grades.examScores': 'Điểm thi',
    'grades.assignmentScores': 'Điểm bài tập',
    'grades.noScores': 'Chưa có điểm',
    'grades.noData': 'Chưa có dữ liệu điểm',
    'grades.noDataDesc': 'Bạn chưa có điểm thi hoặc bài tập',
    'grades.selectCourseFirst': 'Vui lòng chọn khóa học',
    'grades.selectCourseFirstDesc': 'Chọn một khóa học để xem bảng điểm',
    'grades.yourGrades': 'Điểm của bạn',
    'grades.averageScore': 'Điểm trung bình',
    'grades.highestScore': 'Điểm cao nhất',
    'grades.lowestScore': 'Điểm thấp nhất',
    'grades.totalExams': 'Tổng số bài thi',
    'grades.totalAssignments': 'Tổng số bài tập',
    'grades.exam': 'Bài thi',
    'grades.assignment': 'Bài tập',
    'grades.score': 'Điểm số',
    'grades.feedback': 'Nhận xét',
    'grades.noFeedback': 'Không có nhận xét',
    'grades.date': 'Ngày',
    'grades.rank.excellent': 'Xuất sắc',
    'grades.rank.good': 'Giỏi',
    'grades.rank.prettyGood': 'Khá',
    'grades.rank.average': 'Trung bình',
    'grades.rank.weak': 'Yếu',
    'grades.rank.poor': 'Kém',

    // Notifications
    'notifications.title': 'Thông báo',
    'notifications.empty': 'Không có thông báo nào',
    'notifications.all': 'Tất cả',
    'notifications.unread': 'Chưa đọc',
    'notifications.read': 'Đã đọc',
    'notifications.markAllRead': 'Đánh dấu đã đọc tất cả',
    'notifications.newAssignment': 'Bài tập mới',
    'notifications.newExam': 'Đề thi mới',
    'notifications.gradePosted': 'Có điểm mới',
    'notifications.classUpdate': 'Cập nhật lớp học',
    'notifications.approved': 'Đã được duyệt',
    'notifications.rejected': 'Đã bị từ chối',

    // Language
    'settings.language': 'Ngôn ngữ',
    'settings.vietnamese': 'Tiếng Việt',
    'settings.english': 'English',
  },
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.courses': 'Courses',
    'nav.assignments': 'Assignments',
    'nav.exams': 'Exams',
    'nav.grades': 'Grades',
    'nav.notifications': 'Notifications',
    'nav.profile': 'Profile',
    'nav.joinClass': 'Join Class',

    // Common
    'common.save': 'Save Changes',
    'common.saving': 'Saving...',
    'common.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.search': 'Search',
    'common.verified': 'Verified',
    'common.view': 'View',
    'common.viewAll': 'View All',
    'common.viewDetails': 'View Details',
    'common.points': 'points',
    'common.questions': 'questions',
    'common.active': 'Active',
    'common.draft': 'Draft',
    'common.completed': 'Completed',
    'common.pending': 'Pending',
    'common.total': 'Total',
    'common.processing': 'Processing...',
    'common.noData': 'No data yet',
    'common.comingSoon': 'Coming Soon',
    'common.featureDeveloping': 'Feature is under development',
    'common.pleaseComeBack': 'Please come back later',
    'common.student': 'student',
    'common.students': 'students',
    'common.class': 'class',
    'common.classes': 'classes',
    'common.noClasses': 'No classes available',
    'common.noClassesYet': 'No classes yet',
    'common.joinClass': 'Join Class',
    'common.enterClassCode': 'Enter class code',
    'common.classCode': 'Class Code',
    'common.classCodePlaceholder': 'Enter class code',
    'common.join': 'Join',
    'common.joining': 'Joining...',
    'common.joinSuccess': 'Joined class successfully!',
    'common.joinFailed': 'Failed to join class',
    'common.invalidCode': 'Invalid class code',
    'common.classNotFound': 'Class not found',
    'common.youJoinedClass': 'You have already joined this class',
    'common.pendingApproval': 'Pending approval',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.teacher': 'Teacher',
    'common.teacherRole': 'Teacher',
    'common.logout': 'Logout',
    'common.settings': 'Settings',

    // Profile
    'profile.title': 'Personal Profile',
    'profile.personal': 'Personal Information',
    'profile.security': 'Security',
    'profile.preferences': 'Preferences',
    'profile.notifications': 'Notifications',
    'profile.name': 'Full Name',
    'profile.email': 'Email',
    'profile.phone': 'Phone Number',
    'profile.address': 'Address',
    'profile.password': 'Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm Password',
    'profile.joinedDate': 'Joined Date',
    'profile.back': 'Back',
    'profile.emailVerified': 'Verified',
    'profile.datePending': '—',
    'profile.updateInfo': 'Update your information',
    'profile.accountSecurity': 'Account Security',
    'profile.managePassword': 'Manage password and security',
    'profile.customize': 'Customize your experience',
    'profile.notificationsDesc': 'Manage notifications you receive',
    'profile.languageTitle': 'Language / Ngôn ngữ',
    'profile.saveChanges': 'Save Changes',
    'profile.updatePassword': 'Update Password',
    'profile.passwordTip': 'Leave password fields empty if you do not want to change password',
    'profile.enterNewPassword': 'Please enter a new password',
    'profile.currentPasswordRequired': 'Please enter your current password',
    'profile.noEmail': 'Not provided',
    'profile.stats.courses': 'Courses',
    'profile.stats.assignments': 'Assignments',
    'profile.stats.exams': 'Exams',
    'profile.stats.completed': 'Completed',
    'profile.stats.average': 'Average',

    // Toast messages
    'toast.imageType': 'Please select an image file',
    'toast.imageSize': 'Image size must be less than 5MB',
    'toast.avatarSuccess': 'Avatar updated successfully!',
    'toast.uploadFailed': 'Failed to upload image',
    'toast.removeAvatarSuccess': 'Avatar removed successfully!',
    'toast.removeAvatarFailed': 'Failed to remove avatar',
    'toast.passwordMin': 'New password must be at least 6 characters',
    'toast.passwordMismatch': 'New passwords do not match',
    'toast.updateSuccess': 'Profile updated successfully!',
    'toast.updateFailed': 'Update failed',
    'toast.loadDataFailed': 'Failed to load data',
    'toast.loadCoursesFailed': 'Failed to load courses',
    'toast.loadAssignmentsFailed': 'Failed to load assignments',
    'toast.loadExamsFailed': 'Failed to load exams',
    'toast.loadGradesFailed': 'Failed to load grades',
    'toast.logoutSuccess': 'Logged out successfully!',

    // Login
    'login.slogan': 'English Learning & Exam System',
    'login.welcomeBack': 'Welcome Back',
    'login.signInToContinue': 'Sign in to continue',
    'login.createAccount': 'Create Account',
    'login.joinToday': 'Join us today',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.fullName': 'Full Name',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.orContinueWith': 'or continue with',
    'login.continueWithGoogle': 'Continue with Google',
    'login.dontHaveAccount': "Don't have an account?",
    'login.alreadyHaveAccount': 'Already have an account?',
    'login.signUp': 'Sign Up',
    'login.signInLink': 'Sign In',
    'login.demoAccount': 'Demo Account',
    'login.resetPasswordDesc': 'Enter your email to receive a password reset link',
    'login.enterEmail': 'Enter your email',
    'login.sendResetLink': 'Send Reset Link',
    'login.resetEmailSent': 'Password reset link sent!',
    'login.resetEmailNote': 'Please check your email inbox',
    'login.googleNotConfigured': 'Google login requires Supabase configuration',
    'toast.welcomeBack': 'Welcome back!',
    'toast.accountCreated': 'Account created successfully!',
    'toast.loginFailed': 'Login failed',
    'toast.registrationFailed': 'Registration failed',
    'auth.sessionExpired': 'Your session has expired. Please login again.',

    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.student': 'Student',
    'dashboard.yourCourses': 'Your Courses',
    'dashboard.yourAssignments': 'Your Assignments',
    'dashboard.upcomingExams': 'Upcoming Exams',
    'dashboard.recentGrades': 'Recent Grades',
    'dashboard.goodMorning': 'Good Morning',
    'dashboard.goodAfternoon': 'Good Afternoon',
    'dashboard.goodEvening': 'Good Evening',
    'dashboard.totalCourses': 'Total Courses',
    'dashboard.pendingAssignments': 'Pending Assignments',
    'dashboard.completedExams': 'Completed Exams',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.joinNewClass': 'Join New Class',
    'dashboard.viewGrades': 'View Grades',
    'dashboard.viewAssignments': 'View Assignments',
    'dashboard.viewExams': 'View Exams',
    'dashboard.noCourses': 'No courses yet',
    'dashboard.noCoursesDesc': 'Join a class to get started',
    'dashboard.noData': 'No data yet',
    'dashboard.joinClassStart': 'Join a class to get started',

    // Courses
    'courses.title': 'Courses',
    'courses.myCourses': 'My Courses',
    'courses.className': 'Class Name',
    'courses.teacher': 'Teacher',
    'courses.students': 'Students',
    'courses.assignments': 'Assignments',
    'courses.exams': 'Exams',
    'courses.empty': 'No courses yet',
    'courses.emptyDesc': 'Join a class to get started',
    'courses.searchPlaceholder': 'Search courses...',
    'courses.joinClass': 'Join Class',
    'courses.courseCount': 'courses',
    'courses.viewDetails': 'View Details',

    // Assignments
    'assignments.title': 'Assignments',
    'assignments.myAssignments': 'My Assignments',
    'assignments.dueDate': 'Due Date',
    'assignments.totalPoints': 'Total Points',
    'assignments.yourScore': 'Your Score',
    'assignments.submitted': 'Submitted',
    'assignments.notSubmitted': 'Not Submitted',
    'assignments.graded': 'Graded',
    'assignments.pending': 'Pending',
    'assignments.empty': 'No assignments yet',
    'assignments.emptyDesc': 'You have no assignments in joined classes',
    'assignments.searchPlaceholder': 'Search assignments...',
    'assignments.allAssignments': 'All Assignments',
    'assignments.assignmentCount': 'assignments',
    'assignments.class': 'Class',
    'assignments.noDueDate': 'No due date',
    'assignments.overdue': 'Overdue',
    'assignments.turnIn': 'Turn In',
    'assignments.viewSubmission': 'View Submission',

    // Exams
    'exams.title': 'Exams',
    'exams.myExams': 'My Exams',
    'exams.duration': 'Duration',
    'exams.questions': 'Questions',
    'exams.startTime': 'Start Time',
    'exams.endTime': 'End Time',
    'exams.totalPoints': 'Total Points',
    'exams.yourScore': 'Your Score',
    'exams.status': 'Status',
    'exams.all': 'All',
    'exams.active': 'Active',
    'exams.closed': 'Closed',
    'exams.draft': 'Draft',
    'exams.submitted': 'Submitted',
    'exams.notSubmitted': 'Not Submitted',
    'exams.viewResults': 'View Results',
    'exams.takeExam': 'Take Exam',
    'exams.empty': 'No exams yet',
    'exams.emptyDesc': 'You have no exams in joined classes',
    'exams.searchPlaceholder': 'Search exams...',
    'exams.allExams': 'All Exams',
    'exams.examCount': 'exams',
    'exams.upcoming': 'Upcoming',
    'exams.inProgress': 'In Progress',
    'exams.completed': 'Completed',
    'exams.notStarted': 'Not Started',
    'exams.timeRemaining': 'Time Remaining',
    'exams.startExam': 'Start Exam',
    'exams.submitExam': 'Submit Exam',
    'exams.confirmSubmit': 'Are you sure you want to submit?',
    'exams.examCode': 'Exam Code',

    // Grades
    'grades.title': 'Gradebook',
    'grades.subtitle': 'View and track your grades',
    'grades.selectCourse': 'Select a course',
    'grades.noGrades': 'No grades yet',
    'grades.noGradesDesc': 'You have no grades in joined classes',
    'grades.searchPlaceholder': 'Search grades...',
    'grades.studentList': 'Gradebook',
    'grades.students': 'students',
    'grades.exams': 'exams',
    'grades.assignments': 'assignments',
    'grades.examScores': 'Exam Scores',
    'grades.assignmentScores': 'Assignment Scores',
    'grades.noScores': 'No scores yet',
    'grades.noData': 'No grade data',
    'grades.noDataDesc': 'You have no exam or assignment scores',
    'grades.selectCourseFirst': 'Please select a course',
    'grades.selectCourseFirstDesc': 'Select a course to view the gradebook',
    'grades.yourGrades': 'Your Grades',
    'grades.averageScore': 'Average Score',
    'grades.highestScore': 'Highest Score',
    'grades.lowestScore': 'Lowest Score',
    'grades.totalExams': 'Total Exams',
    'grades.totalAssignments': 'Total Assignments',
    'grades.exam': 'Exam',
    'grades.assignment': 'Assignment',
    'grades.score': 'Score',
    'grades.feedback': 'Feedback',
    'grades.noFeedback': 'No feedback',
    'grades.date': 'Date',
    'grades.rank.excellent': 'Excellent',
    'grades.rank.good': 'Good',
    'grades.rank.prettyGood': 'Pretty Good',
    'grades.rank.average': 'Average',
    'grades.rank.weak': 'Weak',
    'grades.rank.poor': 'Poor',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.empty': 'No notifications',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.read': 'Read',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.newAssignment': 'New Assignment',
    'notifications.newExam': 'New Exam',
    'notifications.gradePosted': 'New Grade Posted',
    'notifications.classUpdate': 'Class Update',
    'notifications.approved': 'Approved',
    'notifications.rejected': 'Rejected',

    // Language
    'settings.language': 'Language',
    'settings.vietnamese': 'Tiếng Việt',
    'settings.english': 'English',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    if (saved && (saved === 'vi' || saved === 'en')) {
      return saved as Language;
    }
    return 'vi';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
    window.dispatchEvent(new CustomEvent('languageChange', { detail: lang }));
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
